/**
 * 튜토리얼 시나리오 정의.
 *
 * 각 시나리오는 학생이 W2 의 어느 시점에 풀게 되는지에 맞춰 노출되는 Python
 * 개념을 좁게 좁힌다. 학생이 작성하는 코드는 본문 하나이고, 워커가 자동으로
 * MaehwaAgent 서브클래스로 감싸 실행한다 — 클래스 개념을 모르는 단계에서도
 * 게임이 돌아가도록.
 *
 * 시나리오 진입 시점 (W2):
 *   T1 — §3.1 if 문 직후      : 분기 한 줄, 단일 유닛만
 *   T2 — §3.2 for 문 직후      : 반복 + print, 게임 효과는 부수적
 *   T3 — §3.2 for 문 후반      : 모든 유닛 거점 이동 (첫 게임 손맛)
 *   T4 — §3.4 함수 직후        : 헬퍼 함수 정의 + 호출, 1v1 더미 봇 격파
 */

export type CheckerId = 'T1' | 'T2' | 'T3' | 'T4';

export type SlotKey = 'dmr' | 'rifle_1' | 'shield' | 'rifle_2' | 'medic';

export interface StartPositions {
  readonly A: Readonly<Record<SlotKey, readonly [number, number]>>;
  readonly B: Readonly<Record<SlotKey, readonly [number, number]>>;
}

export interface Scenario {
  readonly id: string;
  readonly title: string;
  /** 한 줄 미션 — 패널 상단에 굵게 표시 */
  readonly description: string;
  /** 여러 줄 힌트 — 패널 우측에 펼침. 백틱(`) 안의 단어는 코드 스타일로 렌더 */
  readonly hint: string;
  /** 학생이 편집하는 시작 코드. 이 위에/아래에 워커가 자동 wrapping 을 붙인다. */
  readonly starterCode: string;
  /** 워커가 학생 코드 뒤에 붙일 자동 wrapping. 학생에게는 안 보임. */
  readonly autoWrap: string;
  /** 상대 봇 경로 (마더 레포의 agents/* 중 하나) */
  readonly opponentPath: string;
  /** 통과 조건을 평가하는 체커 ID — viewer/src/tutorial/checkers.ts 가 매칭 */
  readonly checker: CheckerId;
  /** 통과 시 학생에게 보여줄 축하 메시지 */
  readonly passMessage: string;
  /**
   * 시나리오 전용 좁은 맵 텍스트 (engine/maps/default.txt 와 같은 문법).
   * 본 게임 11×7 맵이 아니라 6~7×7 정도의 디오라마 형 맵을 써서 학생이 한 명만
   * 다뤄도 화면이 빈티가 안 나도록 한다.
   */
  readonly mapText: string;
  /**
   * 슬롯별 시작 좌표 — 위 mapText 안의 walkable 타일이어야 한다.
   * 엔진은 항상 5명/팀을 스폰하므로 모든 5개 슬롯을 다 채워야 한다.
   */
  readonly startPositions: StartPositions;
  /**
   * 본 게임의 30라운드 max 를 시나리오 단위로 단축. T1/T2 처럼 게임 효과가
   * 부수적인 시나리오는 4~5 라운드면 충분 — 30라운드를 다 돌리면 학생 입장에서
   * "한 명만 한참 걸어다니다 끝났네…" 인상이 남는다. 시나리오 합격 검증은
   * checker 가 별도로 하므로 일찍 끊어도 무방.
   */
  readonly maxRounds: number;
}

const STANDARD_AUTO_WRAP = `
# === auto-generated by tutorial runner ===
from agents.base_agent import MaehwaAgent

class _StudentAgent(MaehwaAgent):
    def execute_phase(self, game_state):
        take_actions(game_state)

AGENT_CLASS = _StudentAgent
`;

/**
 * 4 시나리오가 공유하는 7×7 디오라마 맵.
 *  - 가운데 한 칸짜리 거점(`*`) 하나 — T3 가 거점 점령으로 합격하기 위해 필요.
 *  - 평지 외 지형 없음: 길찾기·LoS 트랩으로 학생을 헷갈리게 하지 않기 위함.
 *  - 7×7 은 본 게임 11×7 의 절반 면적이라 1 유닛만 움직여도 화면이 차게 보인다.
 */
const TUTORIAL_MAP_TEXT = `.......
.......
.......
...*...
.......
.......
.......
`;

/**
 * 양 팀이 양쪽 가장자리에서 마주보고 시작 — 이동 거리가 짧아 한 페이즈마다
 * 변화가 눈에 띈다. 슬롯 키는 engine/game_engine.py 의 UNIT_ORDER 와 동일.
 */
const TUTORIAL_START_POSITIONS: StartPositions = {
  A: {
    rifle_1: [0, 1],
    shield:  [0, 2],
    dmr:     [0, 3],
    rifle_2: [0, 4],
    medic:   [0, 5],
  },
  B: {
    rifle_1: [6, 1],
    shield:  [6, 2],
    dmr:     [6, 3],
    rifle_2: [6, 4],
    medic:   [6, 5],
  },
};

const T1: Scenario = {
  id: 'T1',
  title: 'T1 — 첫 분기 (if 문)',
  description: '0번 유닛의 체력을 보고 행동을 분기시키세요.',
  hint: [
    'W2 §3.1 시점이라 아직 `for` 문은 모릅니다.',
    '여기선 0번 유닛 한 명만 다룹니다 — `unit = game_state.my_units[0]`.',
    '',
    '미리 알아야 할 속성 (점(.) 으로 꺼내씁니다):',
    '  - `unit.hp` : 현재 체력 (숫자)',
    '  - `unit.max_hp` : 최대 체력 (숫자)',
    '  - `enemy.position` : 적의 좌표 (헥스 위치)',
    '',
    '미션:',
    '  - `unit.hp` 가 `unit.max_hp` 의 절반 이하이면 → `print("도움이 필요!")`',
    '  - 아니면 → `enemy` 쪽으로 이동',
    '    (`unit.action.move_toward(enemy.position)`)',
    '',
    '핵심: `if 조건:` … `else:` 구조를 처음 게임에 적용해보기.',
  ].join('\n'),
  starterCode: `def take_actions(game_state):
    unit = game_state.my_units[0]      # 우리 팀 0번 유닛 (한 명만 다룸)
    enemy = game_state.enemy_units[0]  # 첫 번째 적

    # 미션:
    #   체력이 절반 이하이면 → print("도움이 필요!")
    #   아니면 → enemy 쪽으로 이동
    #
    # 쓸 수 있는 도구:
    #   - if / else
    #   - unit.hp, unit.max_hp                (둘 다 숫자)
    #   - enemy.position                       (적의 좌표)
    #   - unit.action.move_toward(좌표)        (그 방향으로 한 칸 이동)
    pass
`,
  autoWrap: STANDARD_AUTO_WRAP,
  opponentPath: 'agents/dummy_passive.py',
  checker: 'T1',
  passMessage: '합격! 처음으로 게임 안에서 `if` 분기를 사용했어요. 🎉',
  mapText: TUTORIAL_MAP_TEXT,
  startPositions: TUTORIAL_START_POSITIONS,
  // dmr (mov 2) 가 (0,3) → (6,3) 까지 거리 6 → 3라운드면 인접. 여유로 4.
  maxRounds: 4,
};

const T2: Scenario = {
  id: 'T2',
  title: 'T2 — 5명 모두 살펴보기 (for 문)',
  description: '우리 팀 5명의 클래스와 체력을 모두 출력하세요.',
  hint: [
    '`for` 문으로 `game_state.my_units` 의 5명을 한 번에 순회할 수 있습니다.',
    '',
    '미션:',
    '  - 각 `unit` 에 대해 `print(unit.unit_class, unit.hp)`',
    '',
    '게임 효과는 없지만, 매 페이즈마다 우리 팀 상태가 콘솔에 찍힙니다.',
    '`for` + 속성 접근 + `print` 의 조합을 처음 게임에 적용해보기.',
  ].join('\n'),
  starterCode: `def take_actions(game_state):
    # 미션: 우리 팀 5명 각각의 클래스와 체력을 모두 출력
    # 사용할 도구: for, print(), game_state.my_units, unit.unit_class, unit.hp
    pass
`,
  autoWrap: STANDARD_AUTO_WRAP,
  opponentPath: 'agents/dummy_passive.py',
  checker: 'T2',
  passMessage: '합격! `for` 문으로 5명을 모두 다뤘어요. 🎉',
  mapText: TUTORIAL_MAP_TEXT,
  startPositions: TUTORIAL_START_POSITIONS,
  // print 한두 페이즈만 봐도 충분 — 이동도 없음.
  maxRounds: 2,
};

const T3: Scenario = {
  id: 'T3',
  title: 'T3 — 모든 유닛을 거점으로',
  description: '우리 팀 5명을 모두 중앙 거점(*)으로 이동시키세요.',
  hint: [
    '`game_state.my_units` 는 우리 팀 유닛 5명의 리스트입니다.',
    '각 unit 에 대해 `unit.action.move_toward(목표)` 를 호출하면',
    '한 페이즈에 한 칸씩 그 방향으로 이동합니다.',
    '중앙 거점 좌표 : `game_state.map.capture_point_positions[0]`',
    '',
    '`for` 문으로 5명을 순회하면서 같은 명령을 보내면 됩니다.',
  ].join('\n'),
  starterCode: `def take_actions(game_state):
    # 미션: 우리 팀 5명을 모두 중앙 거점(*)으로 이동
    # 사용할 도구: for, game_state.my_units, unit.action.move_toward(목표)
    # 중앙 거점 좌표는 game_state.map.capture_point_positions[0]
    pass
`,
  autoWrap: STANDARD_AUTO_WRAP,
  opponentPath: 'agents/dummy_passive.py',
  checker: 'T3',
  passMessage: '합격! 우리 팀 유닛 중 한 명이 거점에 도착했어요. 🎉',
  mapText: TUTORIAL_MAP_TEXT,
  startPositions: TUTORIAL_START_POSITIONS,
  // 거점 (3,3) 까지 col 0 에서 거리 3. dmr/medic (mov 2~4) 는 1~2라운드, shield/rifle 도 2라운드.
  // 거점 위에 한 라운드 머물러야 gauge 갱신 → 합격 검증되므로 4라운드면 충분.
  maxRounds: 4,
};

const T4: Scenario = {
  id: 'T4',
  title: 'T4 — 헬퍼 함수로 약한 적 찾기',
  description: '`find_weakest` 함수를 작성해 가장 약한 적을 표적으로 지정하세요.',
  hint: [
    '미션은 두 부분:',
    '  1. `find_weakest(units)` 함수 본문 — 가장 hp 가 낮은 유닛 반환',
    '     힌트: `return min(units, key=lambda u: u.hp)` 한 줄이면 끝.',
    '  2. `take_actions` 안에서 `find_weakest(...)` 를 호출해 표적으로.',
    '',
    '상대는 가만히 있는 더미봇 — `find_weakest` 가 작동하면 5명의 우리 팀이',
    '한 명을 집중사격해 차근차근 격파, 결국 승리합니다.',
    '',
    '핵심: 함수 정의 → 호출 → 반환값 사용의 흐름을 게임에서 체험.',
  ].join('\n'),
  starterCode: `def find_weakest(units):
    """미션: units 리스트에서 hp 값이 가장 작은 유닛 한 명을 찾아 return.

    사용할 도구: min() + key 인자, 또는 직접 for 문으로 비교.
    """
    return None  # ← 진짜 약한 유닛 한 명을 반환하도록 바꾸세요


def take_actions(game_state):
    enemies = [e for e in game_state.enemy_units if e.is_alive]
    if not enemies:
        return

    # 미션: find_weakest 를 호출해 약한 적 한 명을 target 에 담으세요.
    target = None  # ← find_weakest(...) 호출 결과로 교체

    if target is None:
        return

    # (이 아래는 그대로 두면 됩니다 — 모든 유닛이 target 을 집중공격)
    for unit in game_state.my_units:
        if not unit.is_alive:
            continue
        unit.action.move_toward(target.position)
        if unit.action.can_attack(target):
            unit.action.attack(target)
`,
  autoWrap: STANDARD_AUTO_WRAP,
  opponentPath: 'agents/dummy_passive.py',
  checker: 'T4',
  passMessage: '합격! 헬퍼 함수가 적의 약점을 정확히 짚어 우리 팀이 승리했어요. 🎉',
  mapText: TUTORIAL_MAP_TEXT,
  startPositions: TUTORIAL_START_POSITIONS,
  // 5명이 dmr (250 hp, def 30) 을 집중사격 — rifle 한 대당 ~200~250 dmg.
  // 이동 거리 좁히는 데 1~2라운드 + 사격 1~2라운드 → 보수적으로 8.
  maxRounds: 8,
};

export const SCENARIOS: readonly Scenario[] = [T1, T2, T3, T4];

export function findScenario(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
